// <auto-generated />
using System;
using Mandatum.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mandatum.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Application.BoardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96cc1e82-b59f-43cf-ab61-244585f2c662")
                        });
                });

            modelBuilder.Entity("Application.TaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoardRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Term")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardRecordId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("578181d8-e7bf-4a38-8cde-c9671e5efe58"),
                            Description = "1",
                            Status = 1,
                            Term = new DateTime(2021, 11, 29, 14, 37, 10, 870, DateTimeKind.Local).AddTicks(8915),
                            Topic = "1"
                        });
                });

            modelBuilder.Entity("Application.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoardRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardRecordId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62486d13-c455-43f8-8ea6-c1b44c0804a8"),
                            Email = "1@gmail.com",
                            Password = "1"
                        });
                });

            modelBuilder.Entity("Application.TaskRecord", b =>
                {
                    b.HasOne("Application.BoardRecord", null)
                        .WithMany("TaskIds")
                        .HasForeignKey("BoardRecordId");
                });

            modelBuilder.Entity("Application.UserRecord", b =>
                {
                    b.HasOne("Application.BoardRecord", null)
                        .WithMany("UserIds")
                        .HasForeignKey("BoardRecordId");
                });

            modelBuilder.Entity("Application.BoardRecord", b =>
                {
                    b.Navigation("TaskIds");

                    b.Navigation("UserIds");
                });
#pragma warning restore 612, 618
        }
    }
}
